services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU16-ubuntu-22.04
    container_name: booking-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD:?set SA_PASSWORD in .env}
      - MSSQL_PID=Developer
    ports:
      - "11433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

  db-init:
    image: mcr.microsoft.com/mssql-tools:latest
    depends_on:
      mssql:
        condition: service_started
    env_file: [.env]
    volumes:
      - ./docker/sql:/sql:ro
    entrypoint: ["/bin/sh","-c"]
    command: >
      set -e;
      echo '== waiting for mssql ==';
      for i in $(seq 1 60); do
        /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "${SA_PASSWORD}" -Q "SELECT 1" && break;
        echo "waiting... ($i/60)"; sleep 5;
      done;
      echo '== running 00_init.sql ==';
      /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "${SA_PASSWORD}" -d master -i /sql/00_init.sql;
      echo 'DB init done.';
    restart: "no"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TU_HOST: ${TU_HOST:-restapi.tu.ac.th}
    container_name: booking-app
    env_file: [.env]
    environment:
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE}"
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"

      SPRING_MAIL_HOST: "${SPRING_MAIL_HOST}"
      SPRING_MAIL_PORT: "${SPRING_MAIL_PORT}"
      SPRING_MAIL_USERNAME: "${SPRING_MAIL_USERNAME}"
      SPRING_MAIL_PASSWORD: "${SPRING_MAIL_PASSWORD}"

      APP_ADMIN_EMAILS: "${APP_ADMIN_EMAILS}"
      APP_OTP_TTL_SECONDS: "${APP_OTP_TTL_SECONDS}"
      APP_OTP_COOLDOWN: "${APP_OTP_COOLDOWN}"
      APP_JWT_SECRET: "${APP_JWT_SECRET}"
      APP_JWT_EXPIRY: "${APP_JWT_EXPIRY}"

      # TU API (ผูกกับโค้ดคุณที่อ่าน APP_TU_*)
      APP_TU_BASE_URL: "${APP_TU_BASE_URL}"
      APP_TU_APPLICATION_KEY: "${APP_TU_APPLICATION_KEY}"

      # กัน protocol TLS
      JAVA_TOOL_OPTIONS: >-
        -Djdk.tls.client.protocols=TLSv1.2
        -Dhttps.protocols=TLSv1.2
    depends_on:
      mssql:
        condition: service_started
      db-init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mssql_data:
